# Generated by Django 5.0.3 on 2024-03-25 13:49

from django.db import migrations, models

import moku.models.user


class Migration(migrations.Migration):
    dependencies = [("moku", "0002_post")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="a little picture to show up on your profile.",
                upload_to=moku.models.user.user_avatar_filename,
                verbose_name="avatar",
            ),
        )
    ]
