# Generated by Django 5.0.3 on 2024-03-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moku', '0008_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipestep',
            name='instructions',
            field=models.CharField(help_text='the instructions for this step of the recipe. try to keep it clear and concise!', max_length=256, verbose_name='step instructions'),
        ),
    ]
