# Generated by Django 5.0.3 on 2024-03-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moku', '0009_alter_recipestep_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(help_text='give the recipe a title, just so you know what the recipe is for.', max_length=64, verbose_name='recipe title'),
        ),
    ]
