# Generated by Django 5.0.3 on 2024-03-27 16:23

from django.db import migrations, models


def migrate_language_setting(apps, schema_editor):
    User = apps.get_model("moku", "User")
    for user in User.objects.all():
        if hasattr(user, "settings"):
            user.language = user.settings.language
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('moku', '0010_alter_recipe_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'english'), ('lio', 'lami lioa'), ('tok', 'toki pona')], default='en', help_text='what language do you want to use moku.blog in?', max_length=16, verbose_name='language'),
        ),
        migrations.RunPython(migrate_language_setting, reverse_code=migrations.RunPython.noop),
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
